# Java 17을 기반으로 하는 Docker 이미지를 사용
FROM openjdk:17-alpine

# Gradle 버전을 환경 변수로 지정
ENV GRADLE_VERSION 8.5

# Gradle 다운로드 및 설치
RUN wget https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip -P /tmp && \
    unzip -d /opt/gradle /tmp/gradle-$GRADLE_VERSION-bin.zip && \
    rm /tmp/gradle-$GRADLE_VERSION-bin.zip

# Gradle 실행 경로를 PATH에 추가
ENV PATH $PATH:/opt/gradle/gradle-$GRADLE_VERSION/bin

# 작업 디렉토리 생성
WORKDIR /app

# 호스트의 소스 코드를 컨테이너로 복사
COPY . .

# auth 모듈을 빌드
RUN cd auth && gradle build

# 빌드된 JAR 파일을 실행
CMD ["java", "-jar", "/app/auth/build/libs/auth-0.0.1.jar"]

