spring:
  profiles:
    active: local
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.springframework.boot: DEBUG
      org.springframework.security: DEBUG
      org.springframework.web: DEBUG
      apache:
        tiles: INFO
    root: INFO
    com.seouldata.fest: DEBUG