name: Build and Deploy Auth Module to EC2

on:
  push:
    branches: [ "dev-auth" ]
  pull_request:
    branches: [ "dev-auth" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
	  
      - name: Make application.yml
        run: |
         cd auth/src/main/resources
         touch ./application-develop.yml
         echo "${{ secrets.AUTH_YML }}" > ./application-develop.yml
        shell: bash	 
   
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Docker build & push to docker repo
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_REPO }}/pyhdotcom .
          docker push ${{ auth-secrets.DOCKER_REPO }}/directors-dev

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        id: deploy
        with:
          host: ${{ secrets.AWS_ACCESS_KEY_ID }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_ACCESS_KEY }}
          envs: GITHUB_SHA
          script: |
           sudo docker rm -f $(docker ps -qa)
           sudo docker pull ${{ auth-secrets.DOCKER_REPO }}/pyhdotcom
           docker-compose -f docker-compose-auth.yml up -d
           docker image prune -f
