name: Build and Deploy to EC2

on:
  push:
    branches: [ "dev-auth", "dev-fest" ]
  pull_request:
    branches: [ "dev-auth", "dev-fest" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      shell: bash

    - name: Build and Test
      run: ./gradlew build
